### ISSUE TITLE
boot gw commit 'blah' fails due to git config not containing user email

### ISSUE THREAD

**Issue by gerardwebb** [amplify-edge/booty#70]
Just getting used to booty...

bug:

when using  ``` booty gw commit 'blah' ```  if the email does not exist in the .git/config it errors with:
 error: author field is required {"app": "booty"}
 
---

repro:

````
git clone git@github.com-gerardwebb:gerardwebb/shared
cd shared
# setup git config to have upstream section
booty gw reg share
booty gw fset amplify-edge

# make a change

# add and commit
booty gw add-all
booty gw commit 'blah'

# git sync and push to origin
booty gw commit 'blah' 
Error: author field is required
Usage:
  booty gw commit [flags]

Examples:
commit <msg>

Flags:
  -h, --help   help for commit

2021-03-03T14:53:38.322+0100    ERROR   booty/main.go:22        error: author field is required {"app": "booty"}

````

.git/config:
````

[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = git@github.com-gerardwebb:gerardwebb/shared
	fetch = +refs/heads/*:refs/remotes/origin/*
[remote "upstream"]
	url = git@github.com-gerardwebb:amplify-edge/shared
	fetch = +refs/heads/*:refs/remotes/upstream/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[user]
	name = gerardwebb
	
````

---

fixes:

1.
**booty gw fset** should also ask for email ? It would then put it into the .git/config as  [user].email value.

or 

2. 
**booty gw commit 'blah'** should not depend on  the .git/config having a [user].email value.

2 is best
-  just comment out the code requiring the author  ( [user].email ) during the booty gw commit 'blah', to keep things flexible for now.

**Comment by alexadhy** [comment]
https://github.com/amplify-edge/booty/blob/master/config/config.reference.json

**Comment by gerardwebb** [comment]
ok, but not sure how you expect it to be used.

seems like a global config that is part of booty config stored on local disk in the Application dir.

**Comment by alexadhy** [comment]
https://github.com/amplify-edge/booty#tinker-tanker
